package client.enums;

public enum Leagues {
    ALBANIA1("Albania 1"),
    ALGERIA1("Algeria 1"),
    ANDORRA1("Andorra 1"),
    ANGOLA1("Angola 1"),
    ARGENTINA1("Argentina 1"),
    ARGENTINA2("Argentina 2"),
    ARMENIA1("Armenia 1"),
    AUSTRALIA1("Australia 1"),
    AUSTRIA1("Austria 1"),
    AUSTRIA2("Austria 2"),
    AZERBAIJAN1("Azerbaijan 1"),
    BAHRAIN1("Bahrain 1"),
    BANGLADESH1("Bangladesh 1"),
    BELARUS1("Belarus 1"),
    BELGIUM1("Belgium 1"),
    BELGIUM2("Belgium 2"),
    BENIN1("Benin 1"),
    BOLIVIA1("Bolivia 1"),
    BOSNIA1("Bosnia 1"),
    BOSNIA2("Bosnia 2"),
    BRAZIL1("Brazil 1"),
    BRAZIL2("Brazil 2"),
    BULGARIA1("Bulgaria 1"),
    BULGARIA2("Bulgaria 2"),
    BURKINAFASO1("Burkina Faso 1"),
    BURUNDI1("Burundi 1"),
    CAMEROON1("Cameroon 1"),
    CANADA1("Canada 1"),
    CHILE1("Chile 1"),
    CHINA1("China 1"),
    COLOMBIA1("Colombia 1"),
    COSTARICA1("Costa Rica 1"),
    CROATIA1("Croatia 1"),
    CROATIA2("Croatia 2"),
    CUBA1("Cuba 1"),
    CYPRUS1("Cyprus 1"),
    CZECHREPUBLIC1("Czech Republic 1"),
    CZECHREPUBLIC2("Czech Republic 2"),
    DENMARK1("Denmark 1"),
    DENMARK2("Denmark 2"),
    ECUADOR1("Ecuador 1"),
    EGYPT1("Egypt 1"),
    ENGLAND1("England 1"),
    ENGLAND2("England 2"),
    ENGLAND3("England 3"),
    ENGLAND4("England 4"),
    ESTONIA1("Estonia 1"),
    FAROEISLANDS1("Faroe Islands 1"),
    FINLAND1("Finland 1"),
    FINLAND2("Finland 2"),
    FRANCE1("France 1"),
    FRANCE2("France 2"),
    FRANCE3("France 3"),
    GABON1("Gabon 1"),
    GAMBIA1("Gambia 1"),
    GEORGIA1("Georgia 1"),
    GERMANY1("Germany 1"),
    GERMANY2("Germany 2"),
    GERMANY3("Germany 3"),
    GHANA1("Ghana 1"),
    GREECE1("Greece 1"),
    GREECE2("Greece 2"),
    GUATEMALA1("Guatemala 1"),
    GUINEA1("Guinea 1"),
    HONDURAS1("Honduras 1"),
    HUNGARY1("Hungary 1"),
    HUNGARY2("Hungary 2"),
    ICELAND1("Iceland 1"),
    INDIA1("India 1"),
    INDONESIA1("Indonesia 1"),
    IRAN1("Iran 1"),
    IRAQ1("Iraq 1"),
    IRELAND1("Ireland 1"),
    ISRAEL1("Israel 1"),
    ISRAEL2("Israel 2"),
    ITALY1("Italy 1"),
    ITALY2("Italy 2"),
    IVORYCOAST1("Ivory Coast 1"),
    JAMAICA1("Jamaica 1"),
    JAPAN1("Japan 1"),
    JAPAN2("Japan 2"),
    KAZAKHSTAN1("Kazakhstan 1"),
    KENYA1("Kenya 1"),
    KOSOVO1("Kosovo 1"),
    KOSOVO2("Kosovo 2"),
    KUWAIT1("Kuwait 1"),
    LATVIA1("Latvia 1"),
    LIECHTENSTEIN1("Liechtenstein 1"),
    LITHUANIA1("Lithuania 1"),
    LUXEMBOURG1("Luxembourg 1"),
    MALI1("Mali 1"),
    MALTA1("Malta 1"),
    MEXICO1("Mexico 1"),
    MEXICO2("Mexico 2"),
    MOLDOVA1("Moldova 1"),
    MONTENEGRO1("Montenegro 1"),
    MOROCCO1("Morocco 1"),
    NETHERLANDS1("Netherlands 1"),
    NETHERLANDS2("Netherlands 2"),
    NEWZEALAND1("New Zealand 1"),
    NIGERIA1("Nigeria 1"),
    NORTHERNIRELAND1("Northern Ireland 1"),
    NORTHMACEDONIA1("North Macedonia 1"),
    NORWAY1("Norway 1"),
    NORWAY2("Norway 2"),
    PANAMA1("Panama 1"),
    PARAGUAY1("Paraguay 1"),
    PERU1("Peru 1"),
    PHILIPPINES1("Philippines 1"),
    POLAND1("Poland 1"),
    POLAND2("Poland 2"),
    PORTUGAL1("Portugal 1"),
    PORTUGAL2("Portugal 2"),
    PORTUGAL3("Portugal 3"),
    QATAR1("Qatar 1"),
    ROMANIA1("Romania 1"),
    ROMANIA2("Romania 2"),
    RUSSIA1("Russia 1"),
    SANMARINO1("San Marino 1"),
    SAUDIARABIA1("Saudi Arabia 1"),
    SAUDIARABIA2("Saudi Arabia 2"),
    SCOTLAND1("Scotland 1"),
    SCOTLAND2("Scotland 2"),
    SENEGAL1("Senegal 1"),
    SERBIA1("Serbia 1"),
    SERBIA2("Serbia 2"),
    SINGAPORE1("Singapore 1"),
    SLOVAKIA1("Slovakia 1"),
    SLOVAKIA2("Slovakia 2"),
    SLOVENIA1("Slovenia 1"),
    SLOVENIA2("Slovenia 2"),
    SOUTHAFRICA1("South Africa 1"),
    SOUTHKOREA1("South Korea 1"),
    SPAIN1("Spain 1"),
    SPAIN2("Spain 2"),
    SPAIN3("Spain 3"),
    SWEDEN1("Sweden 1"),
    SWEDEN2("Sweden 2"),
    SWITZERLAND1("Switzerland 1"),
    SWITZERLAND2("Switzerland 2"),
    THAILAND1("Thailand 1"),
    TOGO1("Togo 1"),
    TUNISIA1("Tunisia 1"),
    TURKEY1("Turkey 1"),
    TURKEY2("Turkey 2"),
    UKRAINE1("Ukraine 1"),
    UKRAINE2("Ukraine 2"),
    UNITEDARABEMIRATES1("United Arab Emirates 1"),
    URUGUAY1("Uruguay 1"),
    URUGUAY2("Uruguay 2"),
    USA1("USA 1"),
    VENEZUELA1("Venezuela 1"),
    VIETNAM1("Vietnam 1"),
    WALES1("Wales 1");

    private String name;

    Leagues(String name) {
        this.name = name.toUpperCase(); // Convert name to uppercase
    }

    public String getName() {
        return this.name;
    }
}
