package client.enums;

public enum Nations {
    Albania("Albania"),
    Algeria("Algeria"),
    Andorra("Andorra"),
    Angola("Angola"),
    AntiguaAndBarbuda("Antigua & Barbuda"),
    Argentina("Argentina"),
    Armenia("Armenia"),
    Aruba("Aruba"),
    Australia("Australia"),
    Austria("Austria"),
    Azerbaijan("Azerbaijan"),
    Bahrain("Bahrain"),
    Bangladesh("Bangladesh"),
    Barbados("Barbados"),
    Belarus("Belarus"),
    Belgium("Belgium"),
    Benin("Benin"),
    Bermuda("Bermuda"),
    Bhutan("Bhutan"),
    Bolivia("Bolivia"),
    BosniaAndHerzegovina("Bosnia and Herzegovina"),
    Botswana("Botswana"),
    Brazil("Brazil"),
    Bulgaria("Bulgaria"),
    BurkinaFaso("Burkina Faso"),
    Burundi("Burundi"),
    Cambodia("Cambodia"),
    Cameroon("Cameroon"),
    Canada("Canada"),
    CapeVerde("Cape Verde"),
    Chad("Chad"),
    Chile("Chile"),
    China("China"),
    Colombia("Colombia"),
    CostaRica("Costa Rica"),
    Croatia("Croatia"),
    Cuba("Cuba"),
    Curacao("Curaçao"),
    Cyprus("Cyprus"),
    CzechRepublic("Czech Republic"),
    Denmark("Denmark"),
    Djibouti("Djibouti"),
    DominicanRepublic("Dominican Republic"),
    DRcongo("DR Congo"),
    Ecuador("Ecuador"),
    Egypt("Egypt"),
    ElSalvador("El Salvador"),
    England("England"),
    Estonia("Estonia"),
    Eswatini("Eswatini"),
    Ethiopia("Ethiopia"),
    FaroeIslands("Faroe Islands"),
    Fiji("Fiji"),
    Finland("Finland"),
    France("France"),
    Gabon("Gabon"),
    Gambia("Gambia"),
    Georgia("Georgia"),
    Germany("Germany"),
    Ghana("Ghana"),
    Gibraltar("Gibraltar"),
    Greece("Greece"),
    Grenada("Grenada"),
    Guatemala("Guatemala"),
    Guinea("Guinea"),
    Haiti("Haiti"),
    Honduras("Honduras"),
    HongKong("Hong Kong"),
    Hungary("Hungary"),
    Iceland("Iceland"),
    India("India"),
    Indonesia("Indonesia"),
    Iran("Iran"),
    Iraq("Iraq"),
    Ireland("Ireland"),
    Israel("Israel"),
    Italy("Italy"),
    IvoryCoast("Ivory Coast"),
    Jamaica("Jamaica"),
    Japan("Japan"),
    Jordan("Jordan"),
    Kazakhstan("Kazakhstan"),
    Kenya("Kenya"),
    Kosovo("Kosovo"),
    Kuwait("Kuwait"),
    Kyrgyzstan("Kyrgyzstan"),
    Laos("Laos"),
    Latvia("Latvia"),
    Lebanon("Lebanon"),
    Lesotho("Lesotho"),
    Liberia("Liberia"),
    Libya("Libya"),
    Liechtenstein("Liechtenstein"),
    Lithuania("Lithuania"),
    Luxembourg("Luxembourg"),
    Macao("Macao"),
    Malawi("Malawi"),
    Malaysia("Malaysia"),
    Maldives("Maldives"),
    Mali("Mali"),
    Malta("Malta"),
    Mauritania("Mauritania"),
    Mauritius("Mauritius"),
    Mexico("Mexico"),
    Moldova("Moldova"),
    Mongolia("Mongolia"),
    Montenegro("Montenegro"),
    Morocco("Morocco"),
    Mozambique("Mozambique"),
    Myanmar("Myanmar"),
    Namibia("Namibia"),
    Netherlands("Netherlands"),
    NewZealand("New Zealand"),
    Nicaragua("Nicaragua"),
    Niger("Niger"),
    Nigeria("Nigeria"),
    NorthernIreland("Northern Ireland"),
    NorthMacedonia("North Macedonia"),
    Norway("Norway"),
    Oman("Oman"),
    Pakistan("Pakistan"),
    Palestine("Palestine"),
    Panama("Panama"),
    Paraguay("Paraguay"),
    Peru("Peru"),
    Philippines("Philippines"),
    Poland("Poland"),
    Portugal("Portugal"),
    Qatar("Qatar"),
    RepublicOfTheCongo("Republic of the Congo"),
    Reunion("Réunion"),
    Romania("Romania"),
    Russia("Russia"),
    Rwanda("Rwanda"),
    SanMarino("San Marino"),
    SaoTomeAndPrincipe("São Tomé and Príncipe"),
    SaudiArabia("Saudi Arabia"),
    Scotland("Scotland"),
    Senegal("Senegal"),
    Serbia("Serbia"),
    Seychelles("Seychelles"),
    SierraLeone("Sierra Leone"),
    Singapore("Singapore"),
    Slovakia("Slovakia"),
    Slovenia("Slovenia"),
    Somalia("Somalia"),
    SouthAfrica("South Africa"),
    SouthKorea("South Korea"),
    Spain("Spain"),
    SriLanka("Sri Lanka"),
    Sudan("Sudan"),
    Suriname("Suriname"),
    Sweden("Sweden"),
    Switzerland("Switzerland"),
    Syria("Syria"),
    Taiwan("Taiwan"),
    Tajikistan("Tajikistan"),
    Tanzania("Tanzania"),
    Thailand("Thailand"),
    Togo("Togo"),
    TrinidadAndTobago("Trinidad and Tobago"),
    Tunisia("Tunisia"),
    Turkey("Turkey"),
    Turkmenistan("Turkmenistan"),
    Uganda("Uganda"),
    Ukraine("Ukraine"),
    UnitedArabEmirates("United Arab Emirates"),
    Uruguay("Uruguay"),
    USA("USA"),
    Uzbekistan("Uzbekistan"),
    Venezuela("Venezuela"),
    Vietnam("Vietnam"),
    Wales("Wales"),
    Yemen("Yemen"),
    Zambia("Zambia"),
    Zimbabwe("Zimbabwe");

    private String name;

    Nations(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }
}
